apiVersion: v1
kind: ConfigMap
metadata:
  name: eventhub-config
data:
  DB_HOST: "postgres-service"
  DB_PORT: "5432"
  DB_NAME: "eventhub"
  DEBUG: "False"
  ALLOWED_HOSTS: "*"
  CORS_ALLOWED_ORIGINS: "http://localhost:5173"
