# NOTE : En production, ce fichier ne devrait pas être versionné, les valeurs base64 n'étant pas chiffrées.
# Ici, ces credentials ne protègent qu'un cluster Minikube local non exposé publiquement, avec aucune donnée sensible.

apiVersion: v1
kind: Secret
metadata:
  name: eventhub-secret
type: Opaque
data:
  db-password: ZXZlbnRodWJfcGFzc3dvcmQ=
  db-user: ZXZlbnRodWJfdXNlcg==
  django-secret-key: ZXZlbnRodWItcHJvZC1zZWNyZXQta2V5LWNoYW5nZS1tZS0xMjM=
  jwt-secret: ZXZlbnRodWItcHJvZC1zZWNyZXQta2V5LWNoYW5nZS1tZS0xMjM=
  