apiVersion: v1
kind: ServiceAccount
metadata:
  name: django-sa
  namespace: default
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: node-sa
  namespace: default
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: postgres-sa
  namespace: default

